// Generated by CoffeeScript 1.6.3
(function() {
  var Inputer;

  Inputer = (function() {
    function Inputer(loc) {
      this.draw = d3.select(loc);
      this.form = this.draw.append('form');
      this.numElements = 0;
      this.els = [];
      this.buttons = [];
    }

    Inputer.prototype.createTextField = function(name, val) {
      var currentPos;
      currentPos = this.els.length;
      this.els[currentPos] = this.form.append('input').attr('type', 'text').attr('name', name).attr('value', val).attr('id', '' + currentPos);
      return currentPos;
    };

    Inputer.prototype.createLabel = function(text) {
      return this.form.append('text').text(text);
    };

    Inputer.prototype.getTextField = function(ind) {
      return $('#' + ind).val();
    };

    Inputer.prototype.getNewButton = function() {
      var currentPos;
      currentPos = this.buttons.length;
      this.buttons[currentPos] = this.form.append('input').attr('type', 'button');
      return this.buttons[currentPos];
    };

    return Inputer;

  })();

  this.Inputer = Inputer;

}).call(this);
