// Generated by CoffeeScript 1.6.3
(function() {
  var Collider;

  Collider = (function() {
    function Collider() {
      this.x1 = 0;
      this.x2 = 0;
    }

    Collider.prototype.circleAndHorizontalLine = function(c, l) {
      var bottom, cx, cy, leftMargin, r, rightMargin, top, y;
      this.x1 = l.attr('x1');
      this.x2 = l.attr('x2');
      y = l.attr('y1');
      if (y !== l.attr('y2')) {
        alert('invalid line');
      }
      cx = parseInt(c.attr('cx'));
      cy = parseInt(c.attr('cy'));
      r = parseInt(c.attr('r'));
      top = cy - r;
      bottom = cy + r;
      leftMargin = cx - r;
      rightMargin = cx + r;
      if (leftMargin < this.x2 && rightMargin > this.x1) {
        if ((top < y && y < bottom)) {
          return true;
        }
      }
    };

    Collider.prototype.distance = function(ax, ay, bx, yb) {
      return Math.sqrt(Math.pow(bx - ax, 2) + Math.pow(yb - ay, 2));
    };

    return Collider;

  })();

  this.Collider = Collider;

}).call(this);
